### ISSUE TITLE
README.md Feedback

### ISSUE THREAD

**Issue by lisancao** [iRNA-COSI/fair-rna#1]
Great work! The readme is concise and meets all of the Hackseq requirements. 

Some personal notes I have though are (optional): 
- Give your readers an actionable item. I imagine for your particular project that the readme is the first thing people will see, give them a way to check whether their projects meet the standards, or how they can hold the developers of the software they use accountable to it.

**Comment by uniqueg** [comment]
Hi @lisancao, thanks a lot for your feedback! It's a really good idea, but will need some thinking to see if/how we can implement this. The manifesto was written though with a use case in mind in which people use it as a check list. So perhaps we could just add markdown check boxes to each of the guidelines/bullet points and specifically point it out as something that developers of existing tools could go through and see where they stand.

Another idea could be to turn the manifesto into a survey for tool developers to fill out.

**Comment by lisancao** [comment]
Sounds good! Those are all very solid ideas. I know the open source community has a lot of similar guidelines, and sometimes just a small "This package meets the FAIR RNA Standards" can make a package seem more official!
